import type { Pool } from 'pg'

import { collectionName, vectorName } from './vector/query.js'
import type { VectorStore } from './vector/search.js'

/**
 * Provisioning an organization, in one place.
 *
 * Everything else in this system assumes an organization, an administrator, an
 * embedding provider, a workspace and a Qdrant collection already exist. This
 * is what creates them, and it lives in the core rather than beside the `init`
 * CLI because the CLI is one caller and not the definition: a control plane
 * that mints tenants through an API is another, and two implementations of
 * this would be two answers to what a new organization is made of.
 *
 * That is not a hypothetical worry about a future caller. Every field here is
 * read somewhere far away — `organizations.vector_collection` by every read and
 * write on the search path, `layers.provider_id` by the worker to pick which
 * model embeds a document — so a tenant created with one of them missing or
 * disagreeing is a tenant whose every search fails, with nothing in a log.
 *
 * Idempotent, because half-finished state is the normal outcome of a first
 * install: the collection created and the process killed before the workspace.
 * Refusing to continue from that would leave no way forward but manual SQL.
 */

export interface ProvisionOptions {
  readonly slug: string
  readonly name: string
  readonly email: string
  readonly workspace: string
  /**
   * Set on the administrator, when there is one to set.
   *
   * Already hashed rather than a plaintext to hash here: the CLI's arguments
   * end up in a shell history and in `ps`, so the password is generated by the
   * caller and the plaintext exists in exactly one place.
   */
  readonly passwordHash?: string
}

export interface ProviderSpec {
  readonly endpoint: string
  readonly model: string
  readonly dimensions: number
}

export interface ProvisionResult {
  readonly orgId: string
  readonly userId: string
  readonly workspaceId: string
  readonly providerId: string
  /**
   * The provider this organization's layers will actually use.
   *
   * **Not necessarily the one that was asked for.** The installation default is
   * created once and reused by every organization after it, so a second tenant
   * created after somebody changed `NACRE_DEFAULT_EMBEDDING_MODEL` gets the
   * stored one. The collection's slot is built from this and never from the
   * request — see `provisionOrganization`.
   */
  readonly provider: ProviderSpec
  /** The Qdrant collection, as written to `organizations.vector_collection`. */
  readonly collection: string
  /** False when the organization was already there — the call changed nothing. */
  readonly created: boolean
  /**
   * Whether **this call** set the administrator's password.
   *
   * False on every re-run, because the upsert deliberately leaves an existing
   * hash alone. The caller needs to know because it generated a plaintext
   * before calling, and reporting one the database did not accept is worse than
   * reporting nothing: somebody writes it down, discards the real one, and
   * finds out an hour later.
   */
  readonly passwordSet: boolean
}

type Log = (msg: string, extra?: Record<string, unknown>) => void

/**
 * The database half, in one transaction.
 *
 * Separate from the collection so it can be tested without Qdrant, and because
 * idempotency is the property that regresses silently here — the second run of
 * something non-idempotent usually still exits zero.
 */
export async function provisionInPostgres(
  pool: Pool,
  options: ProvisionOptions,
  provider: ProviderSpec,
  collection: string,
  log: Log = () => undefined,
): Promise<Omit<ProvisionResult, 'collection'>> {
  const client = await pool.connect()
  try {
    await client.query('BEGIN')

    const { rows: orgs } = await client.query<{ id: string; existed: boolean }>(
      `WITH ins AS (
         INSERT INTO organizations (slug, name, vector_collection)
         VALUES ($1,$2,$3) ON CONFLICT (slug) DO NOTHING
         RETURNING id
       )
       SELECT id, false AS existed FROM ins
       UNION ALL
       SELECT id, true AS existed FROM organizations WHERE slug = $1
       LIMIT 1`,
      [options.slug, options.name, collection],
    )
    const org = orgs[0]
    if (org === undefined) throw new Error('the organization insert returned no row')
    log(org.existed ? 'organization already existed' : 'organization created', {
      org_id: org.id,
      slug: options.slug,
    })

    // RLS is forced on every tenant table, so everything below this line needs
    // the organization in the transaction-local setting. The organizations row
    // itself is not covered — it is the tenant registry, not tenant data.
    await client.query('SELECT set_config($1, $2, true)', ['app.current_org', org.id])

    const { rows: users } = await client.query<{ id: string; password_set: boolean }>(
      // The password is set only when this call generated one — provisioning
      // over an existing organization must not silently reset the
      // administrator's password and lock them out of their own installation.
      //
      // `password_set` reports whether the COALESCE took this call's value or
      // kept the stored one, by comparing the row as written against what was
      // offered. The caller has a plaintext in hand either way and must not
      // report it when the answer is no: the hash carries its own salt, so two
      // hashes of the same password differ, and equality here can only mean
      // this statement is what put it there.
      `INSERT INTO users (org_id, email, role, password_hash) VALUES ($1,$2,'org_admin',$3)
       ON CONFLICT (org_id, email) DO UPDATE
         SET email = EXCLUDED.email,
             password_hash = COALESCE(users.password_hash, EXCLUDED.password_hash)
       RETURNING id, ($3 IS NOT NULL AND password_hash IS NOT DISTINCT FROM $3) AS password_set`,
      [org.id, options.email, options.passwordHash ?? null],
    )
    const userId = users[0]?.id
    if (userId === undefined) throw new Error('the user insert returned no row')
    log('admin user ready', {
      user_id: userId,
      email: options.email,
      password_set: users[0]?.password_set === true,
    })

    // Shared across organizations by default: one endpoint serves every tenant
    // in a self-hosted install, and a per-organization provider is the
    // exception rather than the shape to create on day one.
    //
    // This row carries `org_id = NULL`, and since 0019 a tenant-scoped role
    // cannot write one — the RESTRICTIVE policies on `embedding_providers`
    // require `org_id = current_setting('app.current_org')`, which NULL fails.
    // That is the point: the installation default is not a tenant's to change.
    // Writing it is a bootstrap act, so this one statement runs under
    // `nacre_worker`, the BYPASSRLS role the worker's queue already uses;
    // `nacre_app` is a member of it (migration 0008), so the switch is
    // available wherever this runs. `SET LOCAL ROLE` reverts at COMMIT, and it
    // is reset immediately below so nothing after it bypasses RLS.
    //
    // **The row is returned rather than only its id**, and that is the fix
    // rather than tidiness. The `WHERE NOT EXISTS` means an existing default is
    // reused and the arguments above are ignored — so the caller's idea of the
    // model and the organization's actual model are two different things the
    // moment somebody changes the configuration between two provisionings. The
    // collection's slot is named after the model, and the worker derives that
    // name from `layers.provider_id`. Built from the argument, a second tenant
    // gets a collection with a slot no layer will ever write to, every document
    // fails in the worker forever, and the API answers `queued`.
    await client.query('SET LOCAL ROLE nacre_worker')
    const { rows: providers } = await client.query<{
      id: string
      endpoint: string
      model: string
      dimensions: number
    }>(
      // Newest, not arbitrary. There can be more than one NULL-`org_id` row:
      // changing the installation default inserts a new one and removes only
      // the unreferenced old ones, because a provider some layer is built on
      // cannot be dropped — those vectors were made by it. `admin-global`'s
      // read already takes the newest and says so; a bare `LIMIT 1` here would
      // have let a tenant created after a model change be provisioned onto the
      // model it replaced, which is the same disagreement one statement later.
      //
      // A data-modifying CTE is not visible to the rest of its own statement,
      // so exactly one branch ever produces rows: `ins` when there was no
      // default, the table when there was.
      `WITH ins AS (
         INSERT INTO embedding_providers (org_id, name, endpoint, model, dimensions)
         SELECT NULL,'default',$1,$2,$3
         WHERE NOT EXISTS (SELECT 1 FROM embedding_providers WHERE org_id IS NULL)
         RETURNING id, endpoint, model, dimensions, created_at
       )
       SELECT id, endpoint, model, dimensions FROM (
         SELECT id, endpoint, model, dimensions, created_at FROM ins
         UNION ALL
         SELECT id, endpoint, model, dimensions, created_at
           FROM embedding_providers WHERE org_id IS NULL
       ) candidates
       ORDER BY created_at DESC, id DESC
       LIMIT 1`,
      [provider.endpoint, provider.model, provider.dimensions],
    )
    await client.query('RESET ROLE')
    const resolved = providers[0]
    if (resolved === undefined) throw new Error('the embedding provider insert returned no row')
    if (resolved.model !== provider.model || Number(resolved.dimensions) !== provider.dimensions) {
      log('the installation default differs from the requested model, and it wins', {
        requested: `${provider.model}/${String(provider.dimensions)}`,
        installation_default: `${resolved.model}/${String(resolved.dimensions)}`,
      })
    }
    log('embedding provider ready', { provider_id: resolved.id, model: resolved.model })

    const { rows: workspaces } = await client.query<{ id: string }>(
      `WITH ins AS (
         -- slug and name take separate parameters despite the same value: slug
         -- is citext, name is text, and Postgres refuses to deduce one type for
         -- a parameter feeding both.
         INSERT INTO workspaces (org_id, slug, name) VALUES ($1,$2,$3)
         ON CONFLICT (org_id, slug) DO NOTHING
         RETURNING id
       )
       SELECT id FROM ins
       UNION ALL
       SELECT id FROM workspaces WHERE org_id = $1 AND slug = $2
       LIMIT 1`,
      [org.id, options.workspace, options.workspace],
    )
    const workspaceId = workspaces[0]?.id
    if (workspaceId === undefined) throw new Error('the workspace insert returned no row')
    log('workspace ready', { workspace_id: workspaceId, slug: options.workspace })

    await client.query('COMMIT')
    return {
      orgId: org.id,
      userId,
      workspaceId,
      providerId: resolved.id,
      provider: {
        endpoint: resolved.endpoint,
        model: resolved.model,
        dimensions: Number(resolved.dimensions),
      },
      created: !org.existed,
      passwordSet: users[0]?.password_set === true,
    }
  } catch (error) {
    await client.query('ROLLBACK').catch(() => {})
    throw error
  } finally {
    client.release()
  }
}

/**
 * Both halves, in the order that survives a failure between them.
 *
 * **Qdrant after Postgres commits.** The reverse can leave a collection
 * belonging to an organization that was rolled back, and the next attempt with
 * the same slug would adopt it.
 *
 * **The slot is named after the provider that was resolved**, never after the
 * one that was asked for. Those differ whenever an installation default already
 * exists and the caller's configuration has moved since — and the failure is
 * silent: the collection is created, the organization looks complete, and the
 * worker writes to a named vector the collection does not have. Checked against
 * a real PostgreSQL and a real Qdrant by provisioning two organizations either
 * side of a model change.
 */
export async function provisionOrganization(
  pool: Pool,
  vectors: Pick<VectorStore, 'ensureCollection'>,
  options: ProvisionOptions,
  provider: ProviderSpec,
  log: Log = () => undefined,
): Promise<ProvisionResult> {
  const collection = collectionName(options.slug)
  const ids = await provisionInPostgres(pool, options, provider, collection, log)

  // `ensureCollection` is already idempotent and already creates the payload
  // indexes, which is the part worth not reimplementing: a filter that falls
  // back to a scan is a latency problem that only appears at volume.
  const slot = vectorName(ids.provider.model, ids.provider.dimensions)
  await vectors.ensureCollection(options.slug, slot, ids.provider.dimensions)
  log('collection ready', { collection, vector: slot, dimensions: ids.provider.dimensions })

  return { ...ids, collection }
}
